### ISSUE TITLE
Uncaught Exception: TypeError: Cannot read property 'setProgressBar' of null - While updating

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-hub#1264]
While updating to 1.2.0 this error occurred:
```
Uncaught Exception:
TypeError: Cannot read property 'setProgressBar' of null
    at MacUpdater.<anonymous> (/Applications/Lisk Hub.app/Contents/Resources/app.asar/build/main.js:64132:16)
    at emitOne (events.js:115:13)
    at MacUpdater.emit (events.js:210:7)
    at ProgressCallbackTransform.streams.push.ProgressCallbackTransform.it [as onProgress] (/Applications/Lisk Hub.app/Contents/Resources/app.asar/build/main.js:53976:175)
    at ProgressCallbackTransform._transform (/Applications/Lisk Hub.app/Contents/Resources/app.asar/build/main.js:5917:22)
    at ProgressCallbackTransform.Transform._read (_stream_transform.js:186:10)
    at ProgressCallbackTransform.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:371:12)
    at writeOrBuffer (_stream_writable.js:357:5)
    at ProgressCallbackTransform.Writable.write (_stream_writable.js:274:11)
    at IncomingMessage.ondata (_stream_readable.js:628:20)
    at emitOne (events.js:115:13)
    at IncomingMessage.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at IncomingMessage.Readable.push (_stream_readable.js:197:10)
```

After restarting Hub application and retrying update it worked fine.

**Comment by slaweet** [comment]
@karek314 Thanks for reporting this bug. It was already tackled in https://github.com/LiskHQ/lisk-hub/issues/1207 so I'm closing this as a duplicate. It was fixed in 1.3.0, so once you are on that one and updating to 1.4.0, it shouldn't happen anymore.
