### ISSUE TITLE
Register integration tests fail randomly

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-hub#1403]
Sometimes this test fail:

```
FAILED TESTS:
  @integration: Register
    Scenario: should allow to create a second passphrase
      ✖ Then I should be logged in
        HeadlessChrome 70.0.3538 (Linux 0.0.0)
      AssertionError: expected activePeerSet to have been called with arguments match(passphrase: punch indicate carbon slush gospel ask museum file actress spawn merit mechanic)
          at Helper.checkIfRegistrationConfirmed (webpack:///test/integration/register.test.js:76:44 <- src/tests.js:403066:58)
          at Context.<anonymous> (webpack:///test/integration/register.test.js:133:52 <- src/tests.js:403154:21)
          at Context.sync (webpack:///node_modules/mocha-steps/lib/step.js:29:0 <- src/tests.js:89665:24)
```
https://jenkins.lisk.io/job/lisk-hub/job/1.5.0/23/consoleFull

**Comment by slaweet** [comment]
I haven't seen this lately, closing.
