### ISSUE TITLE
E2E tests don't work in Chrome 64 on Linux.

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-hub#498]
### Expected behaviour
E2E tests should work in Chrome 64 on Linux because we have Linux on Jenkins and for now have to keep Chrome version to 63.
### Actual behaviour
There is an error in steps that try to go to some url.

### Steps to reproduce
Run `npm run e2e-test` end get an error like this: 
```
  Scenario: should allow to select delegates by URL
  ✔ Given I'm logged in as "delegate candidate"
  ✖ When I go to "/main/voting/vote?votes=standby_27,standby_28,standby_29,nonexisting_22&unvotes=standby_33"
  - And I wait 3 seconds
  - Then I should see text "3 delegate names were successfully resolved for voting." in "upvotes message" element
  - And I should see text "1 of the delegate names selected for unvoting was not currently voted for:standby_33" in "notVotedYet message" element
  - And I should see text "1 of the provided delegate names could not be resolved:nonexisting_22" in "notFound message" element
  - And I should see "vote list" element with text matching regexp:
      """
      standby_2[789]
      standby_2[789]
      standby_2[789]
      """

Failures:

1) Scenario: should allow to select delegates by URL - test/e2e/voting.feature:118
   Step: When I go to "/main/voting/vote?votes=standby_27,standby_28,standby_29,nonexisting_22&unvotes=standby_33" - test/e2e/voting.feature:120
   Step Definition: test/e2e/step_definitions/generic.step.js:158
   Message:
     Error: function timed out after 10000 milliseconds
         at Timeout.<anonymous> (/home/lisk/workspace/lisk-nano_development-E7XJ2DIDO6Q6NQERZPVCTSNDUXYBMEIEVQR4AZNZ7O4UB6E7KJGA/node_modules/cucumber/lib/user_code_runner.js:91:22)
         at ontimeout (timers.js:386:11)
         at tryOnTimeout (timers.js:250:5)
         at Timer.listOnTimeout (timers.js:214:5)
```

**Comment by slaweet** [comment]
Chrome 65 was released and the problem no longer happens in it. So closing this issue.
