### ISSUE TITLE
Investigate why .babelrc is needed

### ISSUE THREAD

**Issue by Efefefef** [LiskHQ/lisk-hub#982]
We should investigate why in my case
starting the webpack server without 'babel-preset-es2015' package and
.babelrc file containing

`{
    "presets": [
        ["es2015", { "modules": false }]
    ]
}`

results in a error

`ERROR in ./src/main.js
Module build failed: Error: Couldn't find preset "es2015" relative to directory "/Users/andreiklimenok"
    at /Users/andreiklimenok/lisk/lisk-hub/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/andreiklimenok/lisk/lisk-hub/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/andreiklimenok/lisk/lisk-hub/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/andreiklimenok/lisk/lisk-hub/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/andreiklimenok/lisk/lisk-hub/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/andreiklimenok/lisk/lisk-hub/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/andreiklimenok/lisk/lisk-hub/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/andreiklimenok/lisk/lisk-hub/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/andreiklimenok/lisk/lisk-hub/node_modules/babel-loader/lib/index.js:50:20)
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 webpack/hot/dev-server ./src/main.js`

**Comment by Efefefef** [comment]
The problem was - babel tries to look for .babelrc in project folder and then in all parent folders subsequentially, and I occasionally had .babelrc in home folder which caused the conflict
https://babeljs.io/docs/en/babelrc.html#lookup-behavior
